name: 'Publish API'
description: 'Publish API to IBM API Connect'
inputs:
  manager-host:  
    description: 'Management hostname'
    required: true
  api-host:  
    description: 'Platform API hostname'
    required: true
  iam-apikey:  
    description: 'IAM API key'
    required: true
  provider-org:  
    description: 'Name of ID of provider org to publish to'
    required: true
  catalog:  
    description: 'Name of ID of catalog to publish to'
    required: true
  product-file:  
    description: 'File name of product yaml to publish'
    required: true
    default: 'product.yaml'
runs:
  using: "composite"
  steps:

  - name: Get APIC Toolkit
    shell: bash
    run: |
      echo "Downloading linux toolkit"
      curl -LO https://${{ inputs.manager-host }}/client-downloads/toolkit-linux.tgz
      pwd
      localdir=$(pwd)
      ls -lah
      ls -ld .
      whoami
      echo "Unpacking linux toolkit"
      cd /tmp/
      tar -zxf $localdir/toolkit-linux.tgz

  - name: Get IAM token
    shell: bash
    run: |
      mkdir ~/.apiconnect/
      touch ~/.apiconnect/token
      ACCESS_TOKEN=$(curl -s "https://iam.cloud.ibm.com/identity/token" -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json' --data "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${{ inputs.iam-apikey}}" | jq .access_token -r)
      echo "${{ inputs.api-host}}/api: |
              refresh_token: \"\"
              access_token: ${ACCESS_TOKEN}" > ~/.apiconnect/token 

  - name: List orgs with apic CLI
    shell: bash
    run: |
      ./apic-slim orgs --accept-license --live-help --my --server ${{ inputs.api-host }}

  - name: Validate product
    shell: bash
    run: |
      ./apic-slim validate ${{ inputs.product-file }}

  - name: Publlish product with apic CLI
    shell: bash
    run: |
      ./apic-slim products:publish --server ${{ inputs.api-host }} --org ${{ inputs.provider-org }} --catalog ${{ inputs.catalog }} ${{ inputs.product-file }}
